version: '2'
services:
  db:
    image: mysql
    environment:
      MYAPP_DATABASE_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
  nginx:
    image: 674273823045.dkr.ecr.us-east-1.amazonaws.com/rdf_dev_nginx:latest
    ports:
      - '8080:80'
      - '80:80'
    volumes_from:
      - storage
    volumes:
      - .:/myapp
  rails:
    build: .
    command: bundle exec rails s unicorn
    links:
      - nginx
    volumes:
      - .:/myapp
      - /data
    volumes_from:
      - storage
    environment:
      BUNDLE_APP_CONFIG: /myapp/.bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
  storage:
    build: containers/storage
    stdin_open: true
    tty: false
    command: /bin/sh

volumes:
  db-data:
    driver: local
