version: '2'
services:
  db:
    image: mysql
    environment:
      MYAPP_DATABASE_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
    #volumes_from:
    #  - storage
  nginx:
    #image: nginx
    build: containers/nginx
    ports:
      - '8080:80'
      - '80:80'
    volumes_from:
      - storage
    links:
      - rails
    volumes:
      - .:/myapp
      - /data
      - /var/log/nginx/log
      - /usr/share/nginx/html
      - /share
  rails:
    build: .
    command: bundle exec unicorn -c config/unicorn.rb
    volumes:
      - .:/myapp
      - /data
    volumes_from:
      - storage
    environment:
      BUNDLE_APP_CONFIG: /myapp/.bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
  storage:
    #build: containers/storage
    image: busybox
    stdin_open: true
    tty: false
    volumes:
      - /data
      - /data:/data
      - .:/myapp
      - /share
      - /var/log
      - /var/run
    command: /bin/sh

#volumes:
#  db-data:
#    driver: local
